# Generated by Django 2.2.6 on 2019-12-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='date_created',
        ),
    ]
